# ids of the dataset from the uciml repo
dataset_ids:
  - 33
  - 45
  - 17
  - 15
  - 174
  - 544

md_param_grid:
    props: [0.75,1.]
    mf_proportions: [0.5,0.75]
    mnar_proportions: [0.,0.25,0.5]

mige_param:
  p_min: 0.85
  p_max: 0.95
  knn: 20
  num_projections: 3

#md_param_grid:
#    props: [0.75]
#    mf_proportions: [0.75]
#    mnar_proportions: [0.5]

# how many runs for each missing data parameter copnfiguration
# where each configuration has the form of:
# (prop, mf_proportion, mnar_proportion)
n_runs: 10